"""Operational state for the label control plane.

Labels live in Iceberg; this is the control plane, which wants point lookups and
small frequent writes rather than table commits. It is also the seam between the
orchestrator and the control site: WAL mode so the site can read while the
orchestrator writes, and one writer per table so they never contend — the
orchestrator owns the run tables, the site owns `review_edit`.

Ids and timestamps are generated by SQLite (`randomblob` / `strftime`) and read
back with `RETURNING`, so two processes cannot mint the same id and no clock
handling is needed on the Mojo side.
"""

from sqlite import Database


comptime SCHEMA = """
CREATE TABLE IF NOT EXISTS pipeline_invocation (
  id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  scene_path  TEXT NOT NULL,
  seed        INTEGER NOT NULL,
  work_dir    TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'pending',
  restate_id  TEXT,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at  TEXT
);

CREATE TABLE IF NOT EXISTS step_run (
  id            TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  invocation_id TEXT NOT NULL REFERENCES pipeline_invocation(id),
  seq           INTEGER NOT NULL,
  step_name     TEXT NOT NULL,
  executor      TEXT NOT NULL,
  status        TEXT NOT NULL,
  params_json   TEXT,
  inputs_json   TEXT,
  outputs_json  TEXT,
  metrics_json  TEXT,
  log_path      TEXT,
  error         TEXT,
  started_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  finished_at   TEXT
);
CREATE INDEX IF NOT EXISTS step_run_by_invocation
  ON step_run (invocation_id, seq);

CREATE TABLE IF NOT EXISTS router_decision (
  id              TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  invocation_id   TEXT NOT NULL REFERENCES pipeline_invocation(id),
  seq             INTEGER NOT NULL,
  candidates_json TEXT NOT NULL,
  chosen          TEXT NOT NULL,
  reason          TEXT,
  model           TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS router_decision_by_invocation
  ON router_decision (invocation_id, seq);

CREATE TABLE IF NOT EXISTS review_task (
  id            TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  invocation_id TEXT NOT NULL REFERENCES pipeline_invocation(id),
  step_run_id   TEXT,
  labels_path   TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'open',
  awakeable_id  TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  resolved_at   TEXT
);

CREATE TABLE IF NOT EXISTS review_edit (
  id             TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  review_task_id TEXT NOT NULL REFERENCES review_task(id),
  track_id       TEXT NOT NULL,
  t              REAL,
  field          TEXT NOT NULL,
  old_value      TEXT,
  new_value      TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- The idempotency ledger: what `RunContext.step()` kept in manifest.json.
-- In the database rather than a JSON file because the manifest was rewritten
-- whole after every step and was last-writer-wins between concurrent runs.
CREATE TABLE IF NOT EXISTS step_ledger (
  work_dir     TEXT NOT NULL,
  step_name    TEXT NOT NULL,
  key          TEXT NOT NULL,
  outputs_json TEXT NOT NULL,
  metrics_json TEXT,
  finished_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (work_dir, step_name)
);
"""


struct OpsDb(Movable):
    """The control-plane database. Open one per process."""

    var db: Database

    def __init__(out self, path: String) raises:
        self.db = Database(path)
        # WAL lets the control site read while the orchestrator writes.
        # `:memory:` does not support WAL and stays in the default mode.
        if path != ":memory:":
            self.db.execute("PRAGMA journal_mode=WAL")
        self.db.execute("PRAGMA foreign_keys=ON")
        # `Database` executes one statement at a time, so the schema is split on
        # `;`. Safe here because no statement contains a quoted semicolon.
        for part in SCHEMA.split(";"):
            var sql = String(String(part).strip())
            if sql.byte_length() > 0:
                self.db.execute(sql)

    def _returning_id(mut self, sql: String, binds: List[String]) raises -> String:
        """Run an INSERT ... RETURNING id and hand back the generated id."""
        var stmt = self.db.prepare(sql)
        for i in range(len(binds)):
            stmt.bind_text(i + 1, binds[i])
        var row = stmt.step()
        if not row:
            raise Error("insert returned no id: " + sql)
        ref r = row.value()
        return r.text_val(0)

    def new_invocation(
        mut self, scene_path: String, seed: Int, work_dir: String
    ) raises -> String:
        var stmt = self.db.prepare(
            "INSERT INTO pipeline_invocation (scene_path, seed, work_dir)"
            " VALUES (?, ?, ?) RETURNING id"
        )
        stmt.bind_text(1, scene_path)
        stmt.bind_int(2, seed)
        stmt.bind_text(3, work_dir)
        var row = stmt.step()
        if not row:
            raise Error("could not create invocation")
        ref r = row.value()
        return r.text_val(0)

    def invocation_exists(mut self, invocation_id: String) raises -> Bool:
        var stmt = self.db.prepare(
            "SELECT 1 FROM pipeline_invocation WHERE id = ?"
        )
        stmt.bind_text(1, invocation_id)
        return Bool(stmt.step())

    def set_invocation_status(
        mut self, invocation_id: String, status: String
    ) raises:
        var stmt = self.db.prepare(
            "UPDATE pipeline_invocation SET status = ?,"
            " updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ?"
        )
        stmt.bind_text(1, status)
        stmt.bind_text(2, invocation_id)
        _ = stmt.step()

    def set_restate_id(mut self, invocation_id: String, restate_id: String) raises:
        var stmt = self.db.prepare(
            "UPDATE pipeline_invocation SET restate_id = ? WHERE id = ?"
        )
        stmt.bind_text(1, restate_id)
        stmt.bind_text(2, invocation_id)
        _ = stmt.step()

    def record_decision(
        mut self,
        invocation_id: String,
        seq: Int,
        candidates_json: String,
        chosen: String,
        reason: String,
        model: String,
    ) raises -> String:
        var stmt = self.db.prepare(
            "INSERT INTO router_decision"
            " (invocation_id, seq, candidates_json, chosen, reason, model)"
            " VALUES (?, ?, ?, ?, ?, ?) RETURNING id"
        )
        stmt.bind_text(1, invocation_id)
        stmt.bind_int(2, seq)
        stmt.bind_text(3, candidates_json)
        stmt.bind_text(4, chosen)
        stmt.bind_text(5, reason)
        stmt.bind_text(6, model)
        var row = stmt.step()
        if not row:
            raise Error("could not record decision")
        ref r = row.value()
        return r.text_val(0)

    def start_step(
        mut self,
        invocation_id: String,
        seq: Int,
        step_name: String,
        executor: String,
        params_json: String,
    ) raises -> String:
        var stmt = self.db.prepare(
            "INSERT INTO step_run"
            " (invocation_id, seq, step_name, executor, status, params_json)"
            " VALUES (?, ?, ?, ?, 'running', ?) RETURNING id"
        )
        stmt.bind_text(1, invocation_id)
        stmt.bind_int(2, seq)
        stmt.bind_text(3, step_name)
        stmt.bind_text(4, executor)
        stmt.bind_text(5, params_json)
        var row = stmt.step()
        if not row:
            raise Error("could not start step")
        ref r = row.value()
        return r.text_val(0)

    def finish_step(
        mut self,
        step_run_id: String,
        status: String,
        outputs_json: String,
        metrics_json: String,
        log_path: String,
        error: String,
    ) raises:
        var stmt = self.db.prepare(
            "UPDATE step_run SET status = ?, outputs_json = ?,"
            " metrics_json = ?, log_path = ?, error = ?,"
            " finished_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')"
            " WHERE id = ?"
        )
        stmt.bind_text(1, status)
        stmt.bind_text(2, outputs_json)
        stmt.bind_text(3, metrics_json)
        stmt.bind_text(4, log_path)
        stmt.bind_text(5, error)
        stmt.bind_text(6, step_run_id)
        _ = stmt.step()

    def next_seq(mut self, invocation_id: String) raises -> Int:
        """One past the highest step sequence for this invocation."""
        var stmt = self.db.prepare(
            "SELECT COALESCE(MAX(seq), -1) + 1 FROM step_run WHERE invocation_id = ?"
        )
        stmt.bind_text(1, invocation_id)
        var row = stmt.step()
        if not row:
            return 0
        ref r = row.value()
        return r.int_val(0)

    # -- the idempotency ledger -------------------------------------------

    def ledger_key(mut self, work_dir: String, step_name: String) raises -> String:
        """The key recorded for this step, or "" if it has never run."""
        var stmt = self.db.prepare(
            "SELECT key FROM step_ledger WHERE work_dir = ? AND step_name = ?"
        )
        stmt.bind_text(1, work_dir)
        stmt.bind_text(2, step_name)
        var row = stmt.step()
        if not row:
            return String("")
        ref r = row.value()
        return r.text_val(0)

    def ledger_outputs(mut self, work_dir: String, step_name: String) raises -> String:
        var stmt = self.db.prepare(
            "SELECT outputs_json FROM step_ledger"
            " WHERE work_dir = ? AND step_name = ?"
        )
        stmt.bind_text(1, work_dir)
        stmt.bind_text(2, step_name)
        var row = stmt.step()
        if not row:
            return String("")
        ref r = row.value()
        return r.text_val(0)

    def record_ledger(
        mut self,
        work_dir: String,
        step_name: String,
        key: String,
        outputs_json: String,
        metrics_json: String,
    ) raises:
        var stmt = self.db.prepare(
            "INSERT INTO step_ledger"
            " (work_dir, step_name, key, outputs_json, metrics_json)"
            " VALUES (?, ?, ?, ?, ?)"
            " ON CONFLICT (work_dir, step_name) DO UPDATE SET"
            " key = excluded.key, outputs_json = excluded.outputs_json,"
            " metrics_json = excluded.metrics_json,"
            " finished_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')"
        )
        stmt.bind_text(1, work_dir)
        stmt.bind_text(2, step_name)
        stmt.bind_text(3, key)
        stmt.bind_text(4, outputs_json)
        stmt.bind_text(5, metrics_json)
        _ = stmt.step()
